"""Proves every Phase 4 component works together on one real sheet — not
just in isolation — by building a small but complete dashboard-style
sheet and confirming the saved .xlsx holds everything correctly.
"""

from openpyxl import load_workbook

from excel_engine.components import (
    add_button,
    add_footer,
    add_kpi_card,
    add_navbar,
    add_progress_bar,
    add_section_header,
    add_title_banner,
)
from excel_engine.components.tables import add_data_table
from excel_engine.core.workbook import ExcelWorkbook
from excel_engine.styles.style_manager import StyleManager


def test_full_dashboard_sheet_composed_from_components(tmp_path):
    style = StyleManager.for_theme("premium")
    workbook = ExcelWorkbook()

    dashboard = workbook.add_sheet("Dashboard")
    add_navbar(dashboard, style, ["Dashboard", "Orders", "Goals"], top_left="A1",
               active="Dashboard", item_width=3)
    add_title_banner(dashboard, style, "Financial OS", subtitle="Auto-calculated",
                      top_left="A2", width=9)
    add_kpi_card(dashboard, style, "Total Revenue", "=SUM(Orders!C2:C50)",
                 top_left="A5", number_format='"₹"#,##0')
    add_button(dashboard, style, "Open Orders", top_left="F5", target_sheet="Orders")
    add_footer(dashboard, style, "Generated by Financial OS v1.0.0", top_left="A20", width=9)

    orders = workbook.add_sheet("Orders")
    add_data_table(orders, style, ["Date", "Customer", "Amount"], n_rows=30, table_name="Orders")

    goals = workbook.add_sheet("Goals")
    add_section_header(goals, style, "Emergency Fund", top_left="A1", width=3)
    goals.set_value("A2", 0.65)
    add_progress_bar(goals, style, "A2:A2")

    out_path = workbook.save(tmp_path / "financial_os.xlsx")

    raw = load_workbook(str(out_path))
    assert raw.sheetnames == ["Dashboard", "Orders", "Goals"]

    dash = raw["Dashboard"]
    assert dash["A1"].value == "Dashboard"          # navbar active item
    assert dash["A2"].value == "Financial OS"         # title banner
    assert dash["A6"].value == "=SUM(Orders!C2:C50)"  # KPI card formula
    assert dash["F5"].hyperlink.target == "#Orders!A1"  # button link
    assert dash["A20"].value == "Generated by Financial OS v1.0.0"

    assert "Orders" in raw["Orders"].tables

    goals_ranges = [str(r.sqref) for r in raw["Goals"].conditional_formatting]
    # single-cell range normalizes to "A2" (no colon) on save/reload
    assert "A2" in goals_ranges
