#!/usr/bin/env python3
"""Build, validate, and package a product for release.

    python scripts/release.py financial_os
    python scripts/release.py financial_os --force   # overwrite an existing release

Produces:
    dist/<product-slug>/
        Financial_OS_v1.0.0.xlsx
        Documentation/README.md
        License/LICENSE.txt
        Release/RELEASE_NOTES.txt

Refuses to overwrite an existing release of the same version unless
--force is given (section 25: "Do not overwrite previous releases
accidentally").
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_REPO_ROOT / "src"))

from products.registry import PRODUCTS  # noqa: E402

from excel_engine.validation import validate_workbook  # noqa: E402


def _slug(name: str) -> str:
    return name.strip().lower().replace(" ", "-")


def release(product_name: str, force: bool = False) -> Path:
    if product_name not in PRODUCTS:
        print(f"Unknown product {product_name!r}. Available: {list(PRODUCTS)}")
        raise SystemExit(1)
    entry = PRODUCTS[product_name]
    config = entry.config

    print(f"Building {config.name} v{config.version}...")
    workbook = entry.build()

    report = validate_workbook(
        workbook, product_name=config.name,
        required_sheets=entry.required_sheets, required_tables=entry.required_tables,
    )
    if not report.passed:
        print(report.format())
        print()
        print("RELEASE ABORTED — workbook failed validation.")
        raise SystemExit(1)
    print("Validation: PASS")

    release_dir = _REPO_ROOT / "dist" / _slug(config.name)
    filename = f"{config.name.replace(' ', '_')}_v{config.version}.xlsx"
    xlsx_path = release_dir / filename

    if xlsx_path.exists() and not force:
        print(f"Release already exists: {xlsx_path}")
        print("Refusing to overwrite. Re-run with --force to replace it.")
        raise SystemExit(1)

    doc_dir = release_dir / "Documentation"
    license_dir = release_dir / "License"
    release_meta_dir = release_dir / "Release"
    for d in (doc_dir, license_dir, release_meta_dir):
        d.mkdir(parents=True, exist_ok=True)

    workbook.save(xlsx_path)

    (doc_dir / "README.md").write_text(
        f"# {config.name} v{config.version}\n\n"
        f"Generated by {config.author} using the Excel Product Engine.\n\n"
        f"Open `{filename}` in Excel (or Google Sheets / LibreOffice Calc).\n"
        f"Every sheet's blue text is yours to edit; black text is "
        f"auto-calculated — leave it as is.\n"
    )
    (license_dir / "LICENSE.txt").write_text(
        "License terms to be finalized.\n\n"
        "This placeholder ships with every release until a real license "
        "is chosen for this product — see the engine repository's own "
        "README for the same open item.\n"
    )
    (release_meta_dir / "RELEASE_NOTES.txt").write_text(
        f"{config.name} v{config.version}\n"
        f"Built: {datetime.now():%Y-%m-%d %H:%M:%S}\n"
        f"Validation: PASS\n"
        f"Sheets: {', '.join(workbook.sheet_names)}\n"
    )

    print()
    print("RELEASE SUCCESSFUL")
    print()
    print(f"  {xlsx_path}")
    print(f"  {doc_dir}/")
    print(f"  {license_dir}/")
    print(f"  {release_meta_dir}/")
    return xlsx_path


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python scripts/release.py <product_name> [--force]")
        print(f"Available products: {list(PRODUCTS)}")
        raise SystemExit(1)
    release(sys.argv[1], force="--force" in sys.argv)


if __name__ == "__main__":
    main()
