"""Workbook-level metadata (maps onto openpyxl's core document properties)."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from openpyxl import Workbook as OpenpyxlWorkbook


@dataclass
class WorkbookMetadata:
    title: str
    author: str = "MuffinCodes"
    version: str = "0.1.0"
    subject: str = ""
    created: datetime = field(default_factory=datetime.now)

    def apply(self, openpyxl_workbook: OpenpyxlWorkbook) -> None:
        """Write these fields onto an openpyxl Workbook's core properties."""
        props = openpyxl_workbook.properties
        props.title = self.title
        props.creator = self.author
        props.subject = self.subject
        props.created = self.created
        props.description = f"Generated by Excel Product Engine v{self.version}"
