from excel_engine.components.footers import add_footer
from excel_engine.core.workbook import ExcelWorkbook
from excel_engine.styles.style_manager import StyleManager


def test_footer_writes_text_and_spans_width():
    wb = ExcelWorkbook()
    ws = wb.add_sheet("Dashboard")
    style = StyleManager.for_theme("premium")
    rng = add_footer(ws, style, "Generated by Financial OS v1.0.0", top_left="A20", width=6)
    assert ws.get_value("A20") == "Generated by Financial OS v1.0.0"
    assert rng.to_a1() == "A20:F20"
    assert ws.raw["A20"].font.italic is True
