from excel_engine.config.product_config import ProductConfig
from excel_engine.core.workbook import ExcelWorkbook
from excel_engine.core.metadata import WorkbookMetadata
from excel_engine.styles.style_manager import StyleManager
from excel_engine.components import (
    add_title_banner,
    add_kpi_card,
    add_navbar,
    add_data_table,
    add_footer,
)

# 1. Describe the product
config = ProductConfig(
    name="Sales Tracker",
    version="1.0.0",
    author="MuffinCodes",
    theme={"name": "premium"},   # or "minimal" / "classic"
)

# 2. Resolve the theme into ready-to-use styles
style = StyleManager.for_theme(config.theme.name)

# 3. Create the workbook
workbook = ExcelWorkbook(
    metadata=WorkbookMetadata(title=config.name, author=config.author, version=config.version)
)

# 4. Build the Dashboard sheet
dashboard = workbook.add_sheet("Dashboard")
add_navbar(dashboard, style, ["Dashboard", "Orders"], top_left="A1",
           active="Dashboard", item_width=3)
add_title_banner(dashboard, style, config.name, subtitle="Auto-calculated",
                  top_left="A2", width=9)
add_kpi_card(dashboard, style, "Total Revenue", "=SUM(Orders!C2:C51)",
             top_left="A5", number_format='"₹"#,##0')
add_kpi_card(dashboard, style, "Total Orders", "=COUNTA(Orders!A2:A51)",
             top_left="E5", number_format="#,##0")
add_footer(dashboard, style, f"Generated by {config.name} v{config.version}",
           top_left="A9", width=9)

# 5. Build the Orders data sheet
orders = workbook.add_sheet("Orders")
add_data_table(orders, style, ["Date", "Customer", "Amount"],
                n_rows=50, table_name="Orders")

# 6. Save
path = workbook.save("output/sales_tracker.xlsx")
print("Saved:", path)
